name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        python-version: [3.9] 
    steps:
    
    - name: build king's valley
      working-directory: ../game/linux
      run: |           
        make
        cp kings ../data
