name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: game/linux    

jobs:
  build:
    runs-on: ubuntu-20.04
       
    steps:
    - uses: actions/checkout@v2
    - name: build king's valley           
      run: |          
        make
        cp kings ../data
