name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
       
    steps:
    
    - name: build king's valley      
      working-directory: ${{ env.working-directory }}game
      run: |          
        make
        cp kings ../data
