name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        python-version: [3.9] 
    steps:
    
    - name: build king's valley      
      run: |  
        working-directory: ${{ env.working-directory }}game/linux
        make
        cp kings ../data
